### ISSUE TITLE
game-off-2016

### ISSUE THREAD

**Issue by AlexKor31** [github/game-off-2016#10]
Hello! I've got a question: what do you mean using word "hacking"? It is not clear enough for me. Is it connected with hackers or security? Or what is that?

**Comment by omn0mn0m** [comment]
I think that they are intending the exact definition used to be open to the game dev. So use whatever defintion of "hacking" you want. In the example, they said "hacking" in terms of cutting down something.

**Comment by leereilly** [comment]
Hi @AlexKor31 - I agree with @omn0mn0m. To elaborate, the following definition might be useful: https://en.wikipedia.org/wiki/Hacking. 

If it helps, my mind immediately goes here when I hear the word "hacking" 💭 
<div align="center">

<img src="http://66.media.tumblr.com/de36b944f1052d17c51d3333b17603c3/tumblr_inline_ntjq9fIfQT1qk1op9_500.gif" width="400">

<img src="http://i0.kym-cdn.com/photos/images/newsfeed/000/123/473/d4cee.gif" width="400">

<img src="http://static.tumblr.com/fe1e6f49c9eb6697f054708e5913412a/g58tavu/srbmhvcg4/tumblr_static_tumblr_m21unt17on1rtnchqo1_500.gif" width="400">

<img src="http://www.slick.productions/secondaryhosting/1-jurassipedia/pictures/visitorcenter/hack.gif" width="400"> 

<img src="http://www.fybertech.net/minecraft/meddle/img/meddlecapitator_short.gif" width="400">

<img src="http://67.media.tumblr.com/04461099380bbee74b817d3471a3ef9a/tumblr_n4wydyQrAq1qh8c35o1_r1_500.gif" width="400">

</div>
