### ISSUE TITLE
Development using GitHub

### ISSUE THREAD

**Issue by RoyBeer** [github/game-off-2016#15]
Hey,

we're a Team that just started development of our game for GameOff 2016. Since we usually use our own git the question came up whether it is stated somewhere or expected that we use GitHub during the development and not only to submit the finished project.

Can you please elaborate on the issue?

**Comment by EtherTyper** [comment]
@RoyBeer They only say to publish to GitHub in the end:

> Push your game source code to your forked repository before Dec 1st.

**Comment by leereilly** [comment]
Hi @RoyBeer - please feel free to use the systems and workflows that your team is already familiar / comfortable with. As @EtherTyper suggested, we just ask that you push your final project to your forked repository on GitHub.

Cheers,
  Lee
