### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by clairemation** [github/game-off-2016#5]
The readme says: "the world will get to enjoy (and maybe even contribute to ... ) your creations." Are we required to release our games under an open-source license?

**Comment by leereilly** [comment]
Hi @clairemation - open source licenses strongly encouraged ✓

**Comment by clairemation** [comment]
Duly noted, thanks!

**Comment by richardkopelow** [comment]
Are we required to keep our game repos linked as a fork? A repo can't be made private if it is still attached to the public repo. (Also my contributions aren't counted on my profile)

**Comment by leereilly** [comment]
@richardkopelow - if you'd like to make the repository private after the jam ends, you can always contact our support team and have it detached from this repository's network. Please see https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork for more information on that.

**Comment by richardkopelow** [comment]
Right-o, thanks!
