### ISSUE TITLE
Clarifying Theme Confusion

### ISSUE THREAD

**Issue by krazysh01** [github/game-off-2016#8]
This may be a redundant question but by saying it must be loosely based on hacking, modding and/or augmenting. Does that imply that the game should NOT use that theme as a core theme?

**Comment by leereilly** [comment]
Hi @krazysh01 - the game can be focused on one of more of those themes e.g. *a game where you thwart computer hacking attempts*, or loosely based on your interpretation e.g. *a game where you hack down soccer players before they shoot on goal*. If it's a reason for participants to hack on their first game project, I'm sure we can find some creative ways to work "hacking" into the storyline :)

HTH!

Cheers,
  Lee
